### ISSUE TITLE
Where are the dependencies?

### ISSUE THREAD

**Issue by boechat107** [RyanMcG/fixturex#1]
Hi, Ryan!

First of all, this is a great library!

But now I'm curious about the dependencies shown on [clojars](https://clojars.org/fixturex/versions/0.3.0). I found them unexpectedly in a conflict with [ultra](https://github.com/venantius/ultra). **fixturex** seems to be using an old version of [puget](https://github.com/greglook/puget), but I could not find it in your project.

**Comment by RyanMcG** [comment]
Hmmm, I'm just using leiningen AFAIK.

I will try to look into this more later, but is it possible you are somehow including dev dependencies?

See if `lein deps :tree` offers any clarity.

**Comment by boechat107** [comment]
The interesting part of the tree:

```
[fixturex "0.3.0"]
  [fixturex/fixturex.context "0.3.0"]
  [fixturex/fixturex.core "0.3.0"]
  [fixturex/fixturex.higher "0.3.0"]
    [mvxcvi/puget "0.6.4"]
        [fipp "0.4.3"]
            [org.clojure/data.finger-tree "0.0.2"]
            [transduce "0.1.0"]
        [org.clojure/data.codec "0.1.0"]
  [mvxcvi/whidbey "0.4.1"]
```

But check the link to clojars in my comment, it goes to your library and its dependencies.

**Comment by RyanMcG** [comment]
Odd. Perhaps it's a bug in repack or an error of my configuration.

**Comment by RyanMcG** [comment]
It seems this was a bug with _lein-repack_ which has since been fixed. I'll publish a patch (0.3.1) as soon as I can (hopefully tonight) without these unnecessary dependencies.

**Comment by boechat107** [comment]
Nice, Ryan!

I guessed it was something with repack too. Good to know it's going to be solved. ;-)

Thanks!

**Comment by RyanMcG** [comment]
Well... I've yet to figure out how to get `lein repack` working again. However, I cut a release using good old `lein release` in the meantime. Feel free to pick up _0.3.1_.

**Comment by RyanMcG** [comment]
[0.3.2](https://clojars.org/fixturex/versions/0.3.2) is a properly repacked release that should work quite well.
